<x-app-layout>
    <div class="col-sm-12">
        <h2>Dashboard is works!</h2>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam fugiat recusandae, maxime beatae vitae voluptas! Ut asperiores qui labore molestiae fuga sunt. Excepturi, similique aliquam itaque quam amet reiciendis modi.</p>
    </div>
</x-app-layout>
